### ISSUE TITLE
New Tilemap Rendering Glitch

### ISSUE THREAD

**Issue by vkeshav300** [vkeshav300/fort-bishop#24]
Glitch Report.

**Describe the bug / glitch**
Proper tiles aren't mapped to corresponding integers from .map file. Works with base.map, not fort-bishop.map
 
**To Reproduce**
1. Launch the program on the post Tile-Map commit version.

**In the code (if applicable):**
*File(s)*: game.cpp, tilemap.h, tilemap.cpp, tilemaps/
*Code Snippet*:
```cpp
/*game.h / game.cpp*/
// Adds tile into ECS & tilemap
void Game::addTile(int srcX, int srcY, int xpos, int ypos) {
    // Creates entity
    auto &tile = manager.addEntity();

    // Adds "TileComponent"
    tile.addComponent<TileComponent>(srcX, srcY, xpos, ypos, textureAtlas);

    // Adds to MAP rendering group
    tile.addGroup(groupMap);
}

/*tilemap.h / tilemap.cpp*/
// Loads a map
void Map::LoadMap(std::string path, int sizeX, int sizeY) {
    char c;
    std::fstream mapFile;
    mapFile.open(path);

    int srcX, srcY;

    for(int x = 0; x < sizeX; x++) {
        for(int y = 0; y < sizeY; y++) {
            mapFile.get(c);
            srcY = atoi(&c) * 32;
            mapFile.get(c);
            srcX = atoi(&c) * 32;
            Game::addTile(srcX, srcY, x * 32, y * 32);
            mapFile.ignore();
        }
    }

    mapFile.close();
}
```
*Conflicting*: Will conflict with future tilemap additions.

**Expected behavior**
Proper tilemap rendering.

**Screenshots**
<img width="597" alt="image" src="https://user-images.githubusercontent.com/70541603/204035464-91f995a5-d7d2-4ee7-bd6b-345d65365e6e.png">

**Computer Information:**
 - OS: Windows 10
 - Most Recent Game Release: v1.2.0

**Additional context:**
Due to improper mapping of integers to textures.

**Comment by vkeshav300** [comment]
After more research, I have found out that the improper rendering is actually due to improper placement of the textures (destRect in tile_component.h). This has nothing to do with improper rendering.

**Comment by vkeshav300** [comment]
I have partially fixed the rendering glitch, rendering a map full of only one type of tile will work.

**Comment by dhruv-reddy-21** [comment]
From now on you can just text me on discord ? I would have fixed this if I
saw this email and it was not buried under like a million useless other
things in my inbox. Just saying.
